import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { library } from "@fortawesome/fontawesome-svg-core";
import {
  faChevronDown,
  faChevronUp,
  faChevronLeft,
  faChevronRight,
  faPlus,
  faMinus,
  faInfoCircle,
  faPen,
  faMapMarkerAlt,
  faThList,
  faTruck,
  faHomeLgAlt,
  faUser as faUserSolid,
  faEnvelope as faEnvelopeSolid,
  faPaperPlane,
  faTrash as faTrashSolid,
  faShareAlt,
  faCartPlus,
  faCheck,
  faCheckDouble,
  faEye,
  faHeart as faHeartSolid,
  faBadgeCheck,
  faCheckCircle,
  faStar as faSolidStar,
} from "@fortawesome/pro-solid-svg-icons";

import {
  faFacebookF,
  faTwitter,
  faInstagram,
  faPinterest,
} from "@fortawesome/free-brands-svg-icons";

import {
  faUser,
  faWrench,
  faBars,
  faLock,
  faMapMarker,
  faEnvelope,
  faPhone,
  faSearch,
  faIndustry,
  faUserTie,
  faQuestionCircle,
  faCamera,
  faExclamationCircle,
  faCogs,
  faBarcode,
  faComments,
  faTrash,
  faCog,
  faFileSpreadsheet,
  faMoneyBill,
  faBalanceScale,
  faRuler,
  faRulerHorizontal,
  faRulerVertical,
  faCopy,
  faHeart,
  faShoppingBag,
  faThumbsUp,
  faTimes,
  faDollarSign,
  faStore,
  faStar,
  faBell,
} from "@fortawesome/pro-regular-svg-icons";

import { faSpinnerThird } from "@fortawesome/pro-duotone-svg-icons";

library.add(
  faChevronDown,
  faChevronUp,
  faChevronLeft,
  faChevronRight,
  faSpinnerThird,
  faUser,
  faDollarSign,
  faWrench,
  faBars,
  faPlus,
  faMinus,
  faLock,
  faMapMarker,
  faEnvelope,
  faPhone,
  faSearch,
  faIndustry,
  faUserTie,
  faQuestionCircle,
  faCamera,
  faExclamationCircle,
  faTimes,
  faCogs,
  faCog,
  faBarcode,
  faComments,
  faTrash,
  faFileSpreadsheet,
  faMoneyBill,
  faBalanceScale,
  faRuler,
  faRulerHorizontal,
  faRulerVertical,
  faCopy,
  faInfoCircle,
  faPen,
  faMapMarkerAlt,
  faThList,
  faTruck,
  faHomeLgAlt,
  faUserSolid,
  faEnvelopeSolid,
  faPaperPlane,
  faTrashSolid,
  faShareAlt,
  faCartPlus,
  faShoppingBag,
  faHeart,
  faFacebookF,
  faTwitter,
  faInstagram,
  faPinterest,
  faThumbsUp,
  faCheck,
  faCheckDouble,
  faEye,
  faHeartSolid,
  faBadgeCheck,
  faCheckCircle,
  faStore,
  faStar,
  faSolidStar,
  faBell
);

export const Icons = {
  menu: {
    wrench: <FontAwesomeIcon icon={["far", "wrench"]} />,
    bars: <FontAwesomeIcon icon={["far", "bars"]} />,
    user: <FontAwesomeIcon icon={["far", "user"]} />,
    userSolid: <FontAwesomeIcon icon={["fas", "user"]} />,
  },
  chevron: {
    up: <FontAwesomeIcon icon={["fas", "chevron-up"]} />,
    down: <FontAwesomeIcon icon={["fas", "chevron-down"]} />,
    left: <FontAwesomeIcon icon={["fas", "chevron-left"]} />,
    right: <FontAwesomeIcon icon={["fas", "chevron-right"]} />,
  },
  bell: <FontAwesomeIcon icon={["far", "bell"]} />,
  star: <FontAwesomeIcon icon={["far", "star"]} />,
  starFilled: <FontAwesomeIcon icon={["fas", "star"]} />,
  envelope: <FontAwesomeIcon icon={["far", "envelope"]} />,
  envelopeSolid: <FontAwesomeIcon icon={["fas", "envelope"]} />,
  lock: <FontAwesomeIcon icon={["far", "lock"]} />,
  plus: <FontAwesomeIcon icon={["fas", "plus"]} />,
  minus: <FontAwesomeIcon icon={["fas", "minus"]} />,
  close: <FontAwesomeIcon icon={["far", "times"]} />,
  trash: <FontAwesomeIcon icon={["far", "trash"]} />,
  trashSolid: <FontAwesomeIcon icon={["fas", "trash"]} />,
  copy: <FontAwesomeIcon icon={["far", "copy"]} />,
  search: <FontAwesomeIcon icon={["far", "search"]} />,
  question: <FontAwesomeIcon icon={["far", "question-circle"]} />,
  camera: <FontAwesomeIcon icon={["far", "camera"]} />,
  exclamation: <FontAwesomeIcon icon={["far", "exclamation-circle"]} />,
  settings: <FontAwesomeIcon icon={["far", "cog"]} />,
  spreadsheet: <FontAwesomeIcon icon={["far", "file-spreadsheet"]} />,
  info: <FontAwesomeIcon icon={["fas", "info-circle"]} />,
  pen: <FontAwesomeIcon icon={["fas", "pen"]} />,
  marker: <FontAwesomeIcon icon={["far", "map-marker"]} />,
  list: <FontAwesomeIcon icon={["fas", "th-list"]} />,
  truck: <FontAwesomeIcon icon={["fas", "truck"]} />,
  home: <FontAwesomeIcon icon={["fas", "home-lg-alt"]} />,
  plane: <FontAwesomeIcon icon={["fas", "paper-plane"]} />,
  share: <FontAwesomeIcon icon={["fas", "share-alt"]} />,
  cartPlus: <FontAwesomeIcon icon={["fas", "cart-plus"]} />,
  heartSolid: <FontAwesomeIcon icon={["fas", "heart"]} />,
  badge: <FontAwesomeIcon icon={["far", "badge"]} />,
  badgeCheck: <FontAwesomeIcon icon={["fas", "badge-check"]} />,
  heart: <FontAwesomeIcon icon={["far", "heart"]} />,

  shoppingcart: <FontAwesomeIcon icon={["far", "shopping-bag"]} />,
  comments: <FontAwesomeIcon icon={["far", "comments"]} />,
  thumbsUp: <FontAwesomeIcon icon={["far", "thumbs-up"]} />,
  loading: <FontAwesomeIcon icon={["fad", "spinner-third"]} spin />,
  dollar: <FontAwesomeIcon icon={["far", "dollar-sign"]} />,
  checkCircle: <FontAwesomeIcon icon={["fas", "check-circle"]} />,
  check: <FontAwesomeIcon icon={["fas", "check"]} />,
  checkDouble: <FontAwesomeIcon icon={["fas", "check-double"]} />,

  store: <FontAwesomeIcon icon={["far", "store"]} />,

  social: {
    facebook: <FontAwesomeIcon icon={["fab", "facebook-f"]} />,
    twitter: <FontAwesomeIcon icon={["fab", "twitter"]} />,
    instagram: <FontAwesomeIcon icon={["fab", "instagram"]} />,
    pinterest: <FontAwesomeIcon icon={["fab", "pinterest"]} />,
  },
};
